[package]
name = "stomper"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
clap = { version = "4", features = ["derive"] }
pcap = "1"
pnet_packet = "0.34"
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0.9", default-features = false, features = ["runtime-tokio", "sqlite"] }
tokio = { version = "1", features = ["full"] }
thiserror = "2"
chrono = { version = "0.4", default-features = false, features = ["clock", "std", "serde"] }

[dev-dependencies]
libc = "0.2"
